baseURL = "/"
languageCode = "es"
title = "La Pitrera"
paginate = 10
enableRobotsTXT = true
defaultContentLanguage = "es"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "¡Sí, la pechera!"
    Content = "Donde se te van los ojos... pero que no se te escape el mensaje ✨"
