baseURL = "/"
languageCode = "es"
title = "La Pitrera"
enableRobotsTXT = true
defaultContentLanguage = "es"

[pagination]
  pagerSize = 10

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "catalanades"
    name = "Catalanades"
    url = "/camisetas/catalanades/"
    weight = 1

  [[menu.main]]
    identifier = "espanolades"
    name = "Españolades"
    url = "/camisetas/espanolades/"
    weight = 2

  [[menu.main]]
    identifier = "sex-love"
    name = "Sex & Love"
    url = "/camisetas/sex-love/"
    weight = 3

  [[menu.main]]
    identifier = "que-se-casa"
    name = "¡Que se casa!"
    url = "/camisetas/que-se-casa/"
    weight = 4

  [[menu.main]]
    identifier = "es-a-mi"
    name = "¿Es a mí?"
    url = "/camisetas/es-a-mi/"
    weight = 5

