collections:
  - name: "camisetas"
    label: "Camisetas"
    folder: "content/camisetas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "number" }
      - { label: "Colección", name: "collection", widget: "select", options: ["filosofos-idos", "catalanades-profundas", "la-reina-de-las-ranas"] }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Borrador", name: "draft", widget: "boolean", default: false }
