backend: 
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "catalanades"
    label: "Catalanades"
    folder: "content/camisetas/catalanades"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "body", widget: "text" }
      - { label: "Precio", name: "price", widget: "string", default: "19.90" }
      - { label: "Imagen", name: "image", widget: "image" }

  - name: "espanolades"
    label: "Españoladas"
    folder: "content/camisetas/espanolades"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "body", widget: "text" }
      - { label: "Precio", name: "price", widget: "string", default: "19.90" }
      - { label: "Imagen", name: "image", widget: "image" }

  - name: "sex-love"
    label: "Sex & Love"
    folder: "content/camisetas/sex-love"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "body", widget: "text" }
      - { label: "Precio", name: "price", widget: "string", default: "19.90" }
      - { label: "Imagen", name: "image", widget: "image" }

  - name: "que-se-casa"
    label: "¡Que se casa!"
    folder: "content/camisetas/que-se-casa"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "body", widget: "text" }
      - { label: "Precio", name: "price", widget: "string", default: "19.90" }
      - { label: "Imagen", name: "image", widget: "image" }

  - name: "es-a-mi"
    label: "¿Es a mí?"
    folder: "content/camisetas/es-a-mi"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "body", widget: "text" }
      - { label: "Precio", name: "price", widget: "string", default: "19.90" }
      - { label: "Imagen", name: "image", widget: "image" }
