backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "camisetas"
    label: "Camisetas"
    folder: "content/camisetas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "string" }
      - { label: "Tema", name: "tema", widget: "select", options: ["Ciencias locas", "Filósofos idos", "¿Estudias o trabajas?", "Yo? Estudio y trabajo", "¡Busco curro!", "Catalanades profundas", "Españoladas profundas", "¿Qué me Queen?", "Socialmente inaceptable", "Dicen! Digo, Diego!", "Como lo lees", "Besito de rana"] }
      - { label: "Imagen", name: "image", widget: "image" }
