backend:
  name: git-gateway
  branch: main

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'camisetas'
    label: 'Camisetas'
    folder: 'content/camisetas'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Precio', name: 'precio', widget: 'number' }
      - { label: 'Imagen', name: 'image', widget: 'image' }
      - { label: 'Descripción', name: 'body', widget: 'markdown' }