backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "camisetas"
    label: "Camisetas"
    folder: "content/camisetas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Tema", name: "tema", widget: "relation", collection: "temas", search_fields: ["title"], value_field: "title", display_fields: ["title"] }

  - name: "temas"
    label: "Temas"
    folder: "content/temas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título del tema", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text", required: false }

  - name: "ganga"
    label: "Ganga con estilazo"
    folder: "content/ganga"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }
      
